language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Arrys
  password:
    secure: G7vAKRna4YJAau7sst4HNqREoiqqDK5W8OmsboEi7BwdcR+kiIoWGKnfqNTvFRPXtuMqX2M7RmB11oe6CkDrTgj+L7qx4AJBp+YnceJ+Ga3d7YSrCxpmLgttJEvGhRUKYc4oY2T3OwwrJKepaQN4Ds691HhxmOS/BEd0w9bIaMmJjxHIgeSRDk6Qwr6jlQ6bzEK+Jds3kz8pm4FnG0oLDleUw9aP93dxL9gMyqVMn499rVahCdOrYb+a7UAq8sq97GYGv+Q5fdr+V9NYNS+1+t9Y+6yajiqtT8CrPXkIgcI+tMZkrATPYppHtyxp80tSNwP1YB0GevsKMuPUVCnpiV2HXiU4mUw3BIYxJLBE+PFjf3FxFr0rG9+7H0yc+2i+0LsB6H/2q4ATU3b4z+yMvkTqZgRpxwx7x6z9jWZrPGTdRWAWflFiw4XYabJd+P076GtFD217SkmR5D6Ra9w0C2u1S2DRkf0VUENClBxxApE8T2KwXJU2USIFAZLAH/n6xrJAohD4Qywu0aBs6+13pf6xs6k+0/GJEIE6rdy63NjeAHKlSZl3GQBI4AUISMU95RiRm5zbWn1n1vi2jjfqz0AMtePGNlmyGkF4T5fU3+/ZnCT0VkrMjREdyIY0cJk8a4JkwM7b0hQEHAO54XjJ3l00U/vur/3TqY3gtqdUBug=
  on:
    tags: true
    repo: ArkadiuszMichalRys/wspr
    python: 3.6
